import type { LegalDocument } from '@/lib/legal-documents';
import { LEGAL_DOCUMENT_PATHS } from '@/lib/legal-documents';

/** StudioLayer AI Privacy Policy — Version 1.0 */
export const PRIVACY_POLICY: LegalDocument = {
  slug: 'privacy',
  path: LEGAL_DOCUMENT_PATHS.privacy,
  title: 'Privacy Policy',
  description: 'How StudioLayer AI collects, uses, and protects your information.',
  effectiveDate: '2026-08-07',
  lastUpdated: '2026-08-07',
  version: '1.0',
  isPublished: true,
  intro: [],
  sections: [
    {
      id: 'introduction',
      title: '1. Introduction',
      paragraphs: [
        'StudioLayer AI is a product operated by 29Copper Media Works.',
        'This Privacy Policy explains how StudioLayer AI ("we", "us", or "our") collects, uses, stores, and protects personal information when you access or use the StudioLayer AI platform, website, applications, and related services (collectively, the "Services").',
        'We are committed to handling personal information responsibly and in accordance with applicable data protection laws.',
        'This Privacy Policy should be read together with our Terms of Service. Where there is a conflict between this Privacy Policy and the Terms of Service regarding privacy matters, this Privacy Policy will govern to the extent of the conflict, except where applicable law requires otherwise.',
        'By creating an account or using the Services, you acknowledge that you have read and understood this Privacy Policy.',
      ],
    },
    {
      id: 'information-we-collect',
      title: '2. Information We Collect',
      paragraphs: [
        'We collect information necessary to operate, secure, and improve the Services. The categories of information we may collect include the following.',
        'Account Information',
        'When you register for an account, we may collect:',
        'your name;',
        'your email address;',
        'your password, which is stored in encrypted form and not retained by us in plain text.',
        'User Content',
        'When you use the Services, we may collect content you provide or generate, including:',
        'images and other files you upload;',
        'AI-generated images and outputs;',
        'refinement history and related creative session data;',
        'assets stored in your Studio Gallery.',
        'Usage Information',
        'We may collect information about how you use the Services, including:',
        'Studio Credit usage and related account activity;',
        'activity logs associated with your account;',
        'feature usage and interaction data within the platform.',
        'Technical Information',
        'When you access the Services, we may automatically collect certain technical information, including:',
        'browser type and settings;',
        'device type and operating system;',
        'IP address and general location derived from it;',
        'log data, timestamps, and diagnostic information related to your use of the Services.',
        'Billing Information',
        'If you purchase paid Services, billing-related information may be processed to manage subscriptions, invoices, and payment status.',
        'Payment card and other sensitive payment details are processed securely by third-party payment providers. StudioLayer AI does not store complete payment card information.',
      ],
    },
    {
      id: 'how-we-use-information',
      title: '3. How We Use Information',
      paragraphs: [
        'We use the information we collect for legitimate business purposes connected to operating and improving the Services, including to:',
        'create and manage user accounts;',
        'authenticate users and maintain account security;',
        'provide AI image generation and related creative functionality;',
        'process image refinements and deliver requested outputs;',
        'operate the Studio Gallery and preserve your creative assets within the Services;',
        'manage billing, subscriptions, and account-related transactions;',
        'detect, prevent, and investigate fraud, abuse, or unauthorized activity;',
        'provide customer support and respond to enquiries;',
        'maintain the security, integrity, and reliability of the Services;',
        'analyze usage patterns to improve product performance and user experience;',
        'comply with applicable legal obligations and enforce our Terms of Service.',
        'We process personal information only where we have a lawful basis to do so under applicable law, such as performance of a contract, legitimate interests, compliance with legal obligations, or consent where required.',
      ],
    },
    {
      id: 'ai-processing',
      title: '4. AI Processing',
      paragraphs: [
        'StudioLayer AI uses artificial intelligence to help users generate, refine, and manage creative content.',
        'Uploaded images and related inputs are processed only to provide the functionality you request, such as generating outputs, applying refinements, or storing assets in your Studio Gallery.',
        'Third-party AI inference providers may temporarily process image data and related inputs while delivering requested services on our behalf. Such processing is limited to providing the functionality you request and is subject to appropriate contractual and security safeguards.',
        'StudioLayer AI does not claim ownership of your uploaded content or AI-generated outputs created through your account, except as necessary to operate the Services under the license described in our Terms of Service.',
        'We do not use your uploaded content or generated outputs to train public AI models unless we expressly inform you otherwise and, where required by law, obtain your consent.',
      ],
    },
    {
      id: 'third-party-services',
      title: '5. Third-Party Services',
      paragraphs: [
        'We rely on trusted third-party service providers to help us operate the Services. These providers may process personal information on our behalf and only as necessary to perform their assigned functions.',
        'Categories of third-party providers may include:',
        'payment processors;',
        'cloud infrastructure providers;',
        'object storage providers;',
        'authentication providers;',
        'AI inference providers;',
        'analytics services;',
        'email and communication providers.',
        'The specific providers we use may change over time as our business, technology, and operational needs evolve. We require service providers that handle personal information to apply appropriate confidentiality and security measures.',
        'Third-party services may have their own privacy practices. We encourage you to review the privacy policies of any third-party services that interact with your account where applicable.',
      ],
    },
    {
      id: 'cookies',
      title: '6. Cookies & Similar Technologies',
      paragraphs: [
        'We use cookies and similar technologies to operate the Services, maintain sessions, remember preferences, and understand how the platform is used.',
        'Cookies are small text files stored on your device when you visit a website or use an online service. Similar technologies may include local storage, session identifiers, and comparable tools used for authentication, security, and functionality.',
        'For complete details about the types of cookies we use, how they are used, and how you can manage them, please refer to our Cookie Policy.',
      ],
    },
    {
      id: 'data-retention',
      title: '7. Data Retention',
      paragraphs: [
        'We retain personal information only for as long as reasonably necessary to fulfill the purposes described in this Privacy Policy, unless a longer retention period is required or permitted by law.',
        'Retention periods may vary depending on the type of information and the purpose for which it was collected, including:',
        'user account information, retained while your account remains active and for a reasonable period thereafter;',
        'generated renders and Studio Gallery assets, retained in accordance with your account settings, product functionality, and applicable billing or grace periods;',
        'billing and transaction records, retained as needed for accounting, tax, fraud prevention, and legal compliance;',
        'system logs and security records, retained for a limited period to support diagnostics, security monitoring, and incident response;',
        'information associated with deleted accounts, which may be deleted or anonymized within a reasonable period, subject to legal or operational requirements;',
        'backup copies, which may persist for a limited time in secure backup systems before being overwritten or deleted in the ordinary course of business.',
        'When information is no longer required, we take reasonable steps to delete, anonymize, or otherwise dispose of it securely.',
      ],
    },
    {
      id: 'user-rights',
      title: '8. User Rights',
      paragraphs: [
        'Depending on your location and applicable law, you may have certain rights regarding your personal information. These rights may include the ability to:',
        'access the personal information we hold about you;',
        'request correction of inaccurate or incomplete information;',
        'update account information through your account settings where available;',
        'delete your account and request deletion of associated personal information, subject to legal and operational retention requirements;',
        'request a copy or export of certain personal information in a portable format, where applicable;',
        'withdraw consent where processing is based on consent, without affecting the lawfulness of processing before withdrawal.',
        'To exercise these rights, please contact us using the details provided in the Contact section below. We may need to verify your identity before responding to certain requests.',
        'You may also have the right to lodge a complaint with a data protection authority in your jurisdiction if you believe our processing of your personal information violates applicable law.',
      ],
    },
    {
      id: 'data-security',
      title: '9. Data Security',
      paragraphs: [
        'We implement reasonable administrative, technical, and organizational safeguards designed to protect personal information against unauthorized access, disclosure, alteration, or destruction.',
        'These measures may include access controls, encryption in transit and at rest where appropriate, monitoring, and internal policies governing data handling.',
        'However, no method of transmission over the internet or method of electronic storage is completely secure. Accordingly, while we strive to protect your information, we cannot guarantee absolute security.',
        'You are responsible for maintaining the confidentiality of your account credentials and for notifying us promptly if you believe your account has been compromised.',
      ],
    },
    {
      id: 'international-users',
      title: '10. International Users',
      paragraphs: [
        'StudioLayer AI is designed for users in multiple countries and regions.',
        'If you access the Services from outside the country where we or our service providers operate, your information may be processed, stored, or transferred in jurisdictions that may have different data protection laws than your country of residence.',
        'Where required by applicable law, we implement appropriate safeguards for international transfers of personal information.',
        'By using the Services, you acknowledge that your information may be processed in countries other than your own.',
      ],
    },
    {
      id: 'childrens-privacy',
      title: '11. Children\'s Privacy',
      paragraphs: [
        'The Services are not intended for individuals who do not meet the minimum age requirements set out in our Terms of Service.',
        'You must be at least 18 years of age, or the age of legal majority in your jurisdiction, whichever is higher, to create an account and use the Services.',
        'We do not knowingly collect personal information from individuals who do not meet these age requirements. If we become aware that we have collected personal information from such an individual, we will take reasonable steps to delete that information.',
        'If you believe a person who does not meet the minimum age requirement has provided us with personal information, please contact us using the details below.',
      ],
    },
    {
      id: 'changes',
      title: '12. Changes to this Privacy Policy',
      paragraphs: [
        'We may update this Privacy Policy from time to time to reflect changes in our Services, legal requirements, or business practices.',
        'When we make changes, we will update the "Last Updated" date and, where appropriate, the version number and Effective Date shown at the top of this document.',
        'If changes are material, we may provide additional notice where required by applicable law.',
        'Your continued use of the Services after the updated Privacy Policy becomes effective constitutes your acceptance of the revised policy, unless applicable law requires a different form of consent.',
      ],
    },
    {
      id: 'contact',
      title: '13. Contact',
      paragraphs: [
        'If you have questions, concerns, or requests regarding this Privacy Policy or our handling of personal information, please contact:',
        'StudioLayer AI',
        'Email: info@studiolayerai.com',
      ],
    },
  ],
};
